---
driver:
  name: ec2
  aws_ssh_key_id: aws-key
  security_group_ids: ["sg-d6fac09a"]
  region: us-east-1
  instance_type: t2.micro
  associate_public_ip: true

provisioner:
  name: shell
  chef_license: accept

platforms:
  - name: bionic64-php
    driver:
      image_id: <put ami id from packer>
transport:
    ssh_key: "<put ssh path to the key that will be used>"
    username: ubuntu

verifier:
  name: inspec

suites:
  - name: default
